services: 
  php: 
    image : php:8.3.9-apache
    container_name: php_getflix
    ports:
      - 8000:80
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
      - getflix_db:/var/lib/mysql 

  db:
      image: mysql:8.0
      container_name: mysql_getflix
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - getflix_db:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: pass 
        MYSQL_DATABASE: GetflixDB
        MYSQL_USER: test
        MYSQL_PASSWORD: pass
      ports:
        - 3307:3306
  
  phpma: 
    image : phpmyadmin/phpmyadmin
    container_name: adminphp
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: pass
      UPLOAD_MAX_FILESIZE: 8M
      POST_MAX_SIZE: 8M
      UPLOAD_LIMIT: 8M
    ports:
      - 8899:80

volumes:
  getflix_db:
    

   